### ISSUE TITLE
Laravel chainable helper methods

### ISSUE THREAD

**Issue by ivanvermeyen** [tightenco/mailthief#18]
Hello!

In my Laravel 5.2 app I created a little trait with some helpers, to call MailThief asserts in the same way as the `see()` and `seeInDatabase()` methods. Perhaps it could be interesting to add helpers like this to your package?

```php
use MailThief\Facades\MailThief;

trait InterceptsEmail
{
    /** @before */
    protected function interceptEmails()
    {
        MailThief::hijack();
    }

    protected function seeEmailFor($email)
    {
        $this->assertTrue(
            MailThief::hasMessageFor($email),
            sprintf('No e-mail was sent to "%s".', $email)
        );

        return $this;
    }

    protected function seeEmailSubject($subject)
    {
        $this->assertEquals(
            $subject, MailThief::lastMessage()->subject,
            sprintf('The e-mail subject does not match "%s".', $subject)
        );

        return $this;
    }

    protected function seeInEmailSubject($subject)
    {
        $this->assertContains(
            $subject, MailThief::lastMessage()->subject,
            sprintf('The e-mail subject does not contain the text "%s".', $subject)
        );

        return $this;
    }
}
```

This allows me to run tests like this:

```php
use Illuminate\Foundation\Testing\DatabaseMigrations;

class RegistrationTest extends TestCase
{
    use DatabaseMigrations;
    use InterceptsEmail;

    /** @test */
    public function a_user_receives_an_activation_mail_after_registering()
    {
        $userData = [
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john@example.com',
        ];

        $this->visit('/nl/login')
            ->type($userData['first_name'], 'first_name')
            ->type($userData['last_name'], 'last_name')
            ->type($userData['email'], 'email')
            ->check('agree')
            ->press('Register');

        $this->see('Thanks')
            ->seeEmailFor($userData['email'])
            ->seeInEmailSubject('Activate')
            ->seeInDatabase('activations', $userData);
    }
}
```

**Comment by michaelachrisco** [comment]
I like this idea of chain-able testing from a View test standpoint. 

How would the above work if the user sends more than one message?

**Comment by ivanvermeyen** [comment]
As far as I can tell, `MailThief::hasMessageFor($email)` checks all e-mails sent
So you could just do `$this->seeEmailFor($email)->seeEmailFor($email)`.

But for getting other info, such as the subject, I think it only has `MailThief::lastMessage()` at the moment. My code just wraps the normal asserts you would do. ;)

**Comment by michaelachrisco** [comment]
Ah I understand now. I feel silly.
How do you feel about tweaking the `seeEmailSubject` and `seeInEmailSubject` methods to `seeInLastEmailSubject` and `seeLastEmailSubject` to indicate which email is being checked. Its a bit pedantic but may be a better indicator to people new to the package that the last message was the one tested. 

Otherwise, I think this would be a great helper. Would this be better served as an extension to Mailthief or integrated into Mailthief?

**Comment by ivanvermeyen** [comment]
You're right, those method names are more appropriate :)
I'm very curious if the MailThief crew finds this useful ;)

**Comment by besologic** [comment]
This is an interesting idea, we'll discuss :)
