### ISSUE TITLE
5.3 compat: PhpStorm whinging with red error: "Function name must be callable - a string, Closure or class implementing __invoke, currently null"

### ISSUE THREAD

**Issue by andzandz** [tightenco/mailthief#32]
Hi, thanks for the 5.3 compat branch!

Anyone else having this error pop up in PhpStorm or other IDEs? MailThief works, so I could ignore it, but it's a little annoying underlining the vendor directory in red.

http://i.imgur.com/bvKyoId.png

**Comment by mattstauffer** [comment]
The big question for me is, A) do we have any contexts in which this callback will be set to `null`, and B) if so, will this code actually run without errors?

Here's what the `send()` method looks like in Laravel itself:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Mail/Mailer.php#L157

Without having actually dug further into this, I would guess that we drop the viability of a `null` `$callback`, but I haven't looked closely at it yet.

**Comment by T3chn0crat** [comment]
I have the current version of phpStorm and I do not get that error.  It also looks like a bug since the same type of call is made in the method above and its not upset about that one.
