### ISSUE TITLE
Support for custom mail headers

### ISSUE THREAD

**Issue by djohnston08** [tightenco/mailthief#33]
I use Sendgrid to send out our mail.  One feature they allow is sending certain headers to categorize mail or send other options.  To set the headers I have to get the underlying swift message, which of course means I cannot use MailThief.  However it would also be great to be able to check for certain headers during our tests.  Do you think this is functionality that should be added?  If so I could look into stubbing that out.  Obviously the whole SwiftMailer would be too extensive, but would headers be a feature we would want to be able to fake some implementation for?

**Comment by mattstauffer** [comment]
Good question. Would you be up to paste a quick sample of what your code looks like here so we can take a look and think about what it would look like to mock the swift instance?

Thanks!

**Comment by patrickguevara** [comment]
Oh hey I need this too. When sending an email with Mailgun, I add a custom variable (through the headers) so that if a message drops, for instance, the webhook callback knows which form to adjust (e.g. indicate that the given email was bad).

```
Mail::send($this->view, compact('form'), function ($m) {
            $m->from('email@example.com', 'Sender');
            $m->subject($this->subject);
            $m->to($this->formEmail);
            $m->getHeaders()->addTextHeader('X-Mailgun-Variables', json_encode(['form_id' => $this->form->id]));
        });
```

I'm actually not asserting against those values, but my tests are failing:
```
Error: Call to undefined method MailThief\Message::getHeaders()
```

I would assume that creating a collection of custom headers would be sufficient for this. I **could** test for their existence but more importantly my tests wouldn't fail because the function doesn't exist.

**Comment by djohnston08** [comment]
Sorry for the delayed response here.  The notification had gotten lost in my email, but this is exactly my use case.  

Only other thing I do some places is:

```php
Mail::send($this->view, compact('form'), function ($m) {
    $m->from('email@example.com', 'Sender');
    $m->subject($this->subject);
    $m->to($this->formEmail);
    $m->getSwiftMessage()->getHeaders()->addTextHeader('X-Mailgun-Variables', json_encode(['form_id' => $this->form->id]));
});
```

Although as the above comment points out I don't think the extra level is truly needed.

**Comment by besologic** [comment]
@djohnston08 Is calling `getSwiftMessage` necessary to add the headers? Or is that more just a syntax preference thing?

**Comment by patrickguevara** [comment]
@besologic It's not necessary. The code I provided works in production. In Illuminate\Mail\Message.php the following makes our code samples equivalent:

```php
    /**
     * Dynamically pass missing methods to the Swift instance.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        $callable = [$this->swift, $method];

        return call_user_func_array($callable, $parameters);
    }
```

**Comment by djohnston08** [comment]
Totally agree.  Like I said at the end of that comment, that's just additional but not needed.

**Comment by djohnston08** [comment]
Thanks guys!
