### ISSUE TITLE
Decide how to handle 5.3

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/mailthief#37]
Talked over this with @adamwathan a bit, but we have to decide how to handle backwards compatibility when 5.3 support means breaking.

There are a few options (separate repo, major version increase, etc.) but my preferred option is to have the package work on both <5.2 and 5.3 going forward, even though it will almost definitely mean sniffing the Laravel version and having different code paths for each. But I'm open.

Thoughts?

**Comment by besologic** [comment]
Based on this PR: https://github.com/tightenco/mailthief/pull/30 it looks like your preferred option seems pretty viable. 

I think we go this route until it becomes untenable, then we can branch and do a major version increase.

**Comment by T3chn0crat** [comment]
:+1: to what @besologic said.

One thing about that PR is its set to require 5.3.  So that would need to be changed.
