### ISSUE TITLE
Closure must be an instance of MailThief\Message, integer given

### ISSUE THREAD

**Issue by IftekherSunny** [tightenco/mailthief#47]
**Laravel Framework version 5.2.45
Mailthief version dev-master**

Getting this error.

```
1) ExampleTest::test_new_users_are_sent_a_welcome_email
TypeError: Argument 1 passed to MailThief\MailThief::MailThief\{closure}() must be an instance of MailThief\Message, integer given

/home/user/code/laravel/vendor/tightenco/mailthief/src/MailThief.php:125
```

**Comment by mattstauffer** [comment]
@IftekherSunny Could you show us what your test looks like?

Thanks!

**Comment by mattstauffer** [comment]
Oh, I think `dev-master` might not be ready for backwards compatibility with Laravel 5.2. You may need to use one of the tagged releases until we release a version that's compatible with both 5.2 and 5.3.

**Comment by IftekherSunny** [comment]
@mattstauffer ok.

**Comment by mcordingley** [comment]
On v0.3.2 with Laravel 5.2 I'm getting "TypeError: Argument 1 passed to App\Models\Observers\User::App\Models\Observers\{closure}() must be an instance of Illuminate\Mail\Message, instance of MailThief\Message given, called in /vagrant/vendor/tightenco/mailthief/src/MailThief.php on line 158"

Is there a particular tagged release that works with 5.2?

**Comment by besologic** [comment]
Tagged release is now out that is compatible with both 5.2 and 5.3.
