### ISSUE TITLE
Multiple mail connections

### ISSUE THREAD

**Issue by nathanjisaac** [tightenco/mailthief#48]
I have a script that requires another mail connection different from the app's default. In my script I am doing something like this: 

``` php
// Backup your default mailer
$backup = Mail::getSwiftMailer();

// Setup your mailer
$transport = Swift_SmtpTransport::newInstance(
    config('custom.mail.host'),
    config('custom.mail.port'),
    config('custom.mail.encryption')
);
$transport->setUsername(config('custom.mail.username'));
$transport->setPassword(config('custom.mail.password'));

$custom = new Swift_Mailer($transport);

// Set the mailer
Mail::setSwiftMailer($custom);

// Send mail
Mail::send();

// Restore your original mailer
Mail::setSwiftMailer($backup);
```

This returns a few errors:

```
Error: Call to undefined method MailThief\MailThief::getSwiftMailer()
Error: Call to undefined method MailThief\MailThief::setSwiftMailer()
```
## Proposed solution

Would a good solution be to add those methods to the `MailThief` class? 

``` php

/**
 * Get the Swift Mailer instance.
 *
 * @return \Swift_Mailer
 */
public function getSwiftMailer()
{
    return $this->swift;
}

/**
 * Set the Swift Mailer instance.
 *
 * @param  \Swift_Mailer  $swift
 * @return void
 */
public function setSwiftMailer($swift)
{
    $this->swift = $swift;
}

```

Or should I be testing this type of thing in a different way?

**Comment by mattstauffer** [comment]
Until now we've rather successfully avoided any direct references to the swift mailer.

I see the need here, but I'm also super cautious' introducing the `getSwiftMailer()` method will certainly introduce folks who expect MailThief to have its own internally-managed Swift mailer, even if we only intended it to be use for folks like you who will be passing in their own swift mailer instance.

Four options I can think of so far:
1. Reject this issue. "Sorry." Not my favorite option.
2. Fix this issue by offering the set and get methods like proposed. Good fit for this test, but will likely introduce confusion to folks elsewhere.
3. Find some alternate in-between method that makes this possible but doesn't confuse folks
4. Give in and build a full swift mailer fake in MailThief that can be accessed like in the mailer itself.

**Comment by nisaac2fly** [comment]
@mattstauffer thank you for your response. 

I'm not sure this is the best way to handle it but I ended up creating a function like this as a workaround. 

```php
private function switchSwiftMailer()
{
    if ($this->laravel->environment() !== 'testing') {
        // Setup mailer
        $transport = Swift_SmtpTransport::newInstance(
            config('custom.mail.host'),
            config('custom.mail.port'),
            config('custom.mail.encryption')
        );
        $transport->setUsername(config('custom.mail.username'));
        $transport->setPassword(config('custom.mail.password'));

        // Set the mailer
        Mail::setSwiftMailer(new Swift_Mailer($transport));
    }
}
```

If there is a better way of handling this I am interested in hearing about it.

**Comment by jausions** [comment]
@nathanjisaac I will venture a comment that might sound rude, but it seems to me that the way you go about it to switch your mailer is not actually proper. Relying on a method not from the `Illuminate\Contracts\Mail\Mailer` is prone to breaking or cause problems (which you already are experiencing.)

I would suggest you use some service provider to return your alternate mailer whenever needed.
