### ISSUE TITLE
Mail not received by MailThief when sending mail in event listener

### ISSUE THREAD

**Issue by jdwit** [tightenco/mailthief#5]
When I write a test for the users.create route where a user gets registered and MailThief tests for receiving the message to "email just registered by user" all is ok.

However, when I implement a event flow, e.g. I fire an event UserWasRegistered, followed by a listener SendVerificationEmail in which the mail is send, the mail sender is not hijacked by MailThief.

In the event listener I don't use the Mail facade but inject Illuminate\Mail\Mailer in the constructor.

**Comment by adamwathan** [comment]
Try injecting `Illuminate\Contracts\Mail\Mailer` instead

**Comment by earnaway** [comment]
Having the same problem as @jdwit, and even though I'm injecting `Illuminate\Contracts\Mail\Mailer` it doesn't seem to be working. You have any luck on this @jdwit?
