### ISSUE TITLE
Event MessageSending not fired

### ISSUE THREAD

**Issue by juniorb2ss** [tightenco/mailthief#52]
Fix simulate fire core event `Illuminate\Mail\Events\MessageSending`

**Comment by calebporzio** [comment]
Hey @juniorb2ss,

So are you depending on this event being fired in your application?

**Comment by mattstauffer** [comment]
@juniorb2ss I'm closing this for now, but please let me know if you (or anyone else who runs into this error in the future via Google) have needs here.
