### ISSUE TITLE
Multiple emails being sent only inspect the last one that went

### ISSUE THREAD

**Issue by jdavidbakr** [tightenco/mailthief#53]
It's pretty common for me to send an email to the end user or a list of end users and then send a report notification to the admin accounts within the same.  I would like to be able to check that both emails were sent, but mailthief only inspects the last message for its tests.  'seeMessageFor' and 'seeMessageWithSubject' implies - to me, at least - that somewhere in the message history is a match for those.

**Comment by besologic** [comment]
Now available: https://github.com/tightenco/mailthief/releases/tag/v0.3.3
