### ISSUE TITLE
MailThief Doesn't Hijack Password Broker

### ISSUE THREAD

**Issue by mcordingley** [tightenco/mailthief#55]
This is in Laravel 5.2, but may also affect 5.3. I'm attempting to test the reset email sent by the framework to make sure it has the correct content. Right now, MailThief is hijacking other emails, but these emails are falling through to the framework's real mail system. The function that's sending this email can be found at `\Illuminate\Auth\Passwords\PasswordBroker::emailResetLink`

**Comment by besologic** [comment]
That method doesn't exist in 5.3, it doesn't seem. I did some brief investigation and it seems like `emailResetLink` is using the mailer that's passed into the constructor, which should be of type `Illuminate\Contracts\Mail\Mailer`. We're specifying MailThief as the instance here: https://github.com/tightenco/mailthief/blob/master/src/MailThief.php#L43, so this should really be working.

If you could put together a failing test, that would definitely speed up the debugging. I'll try to do this when we have some time as well.

**Comment by mcordingley** [comment]
I think the problem is that it gets resolved from the IOC and injected in before MailThief gets a chance to swap out mailers. I've been having trouble tracing this through on the framework end, though.
