### ISSUE TITLE
Mailable compatibility

### ISSUE THREAD

**Issue by jdavidbakr** [tightenco/mailthief#58]
Laravel 5.3 introduced new methods to send mail, but MailThief appears to be incompatible:

```
Mail::to([$user->name=>$user->email])
     ->queue(new ContactSubmissionEmail($contact_submission));
```

results in

```
[Symfony\Component\Debug\Exception\FatalErrorException]  
Call to undefined method MailThief\MailThief::to()
```

**Comment by mattstauffer** [comment]
Thanks @jdavidbakr; you can read our approach to this in the readme:

> If you’re using the new Mailables syntax in Laravel 5.3, you can use the native mail assertions. But if you’re using the classic mail syntax in any version of Laravel, MailThief is still your best option.

**Comment by richstandbrook** [comment]
Trouble with this is that there's no way in the Laravel 5.3 native mail assertions to test the content of an email, but there is in MailThief!
