### ISSUE TITLE
Any chance of support for Laravel/Lumen 5.1?

### ISSUE THREAD

**Issue by earnaway** [tightenco/mailthief#6]
Any chance this would work in earlier versions of Laravel like 5.1 or even support for Lumen?

**Comment by michaelachrisco** [comment]
@earnaway Looks like there isn't much to add to support Laravel 5.1
Branch is here: https://github.com/michaelachrisco/mailthief/tree/dev-laravel-5.1

Perhaps old versions of laravel should live in their own branch? Semantic versioning? Not sure what the best course of action is moving forward, but I added a PR with the work.

**Comment by earnaway** [comment]
Looks good!
I'm still struggling to get it working using `Illuminate\Contracts\Mail\Mailer`, similar to #5 but I'll keep looking into it.

**Comment by ksassnowski** [comment]
Take a look at my PR (#13) regarding support for Lumen.

**Comment by ksassnowski** [comment]
This should be resolved after #13 got merged.

**Comment by mattstauffer** [comment]
👍
