### ISSUE TITLE
Rendered view

### ISSUE THREAD

**Issue by ThibaudDauce** [tightenco/mailthief#60]
Following this commit in Laravel 5.4 https://github.com/laravel/framework/commit/44880dfb6e5e558da8443544bd88515f04c72132#diff-350394a5c5018427fed3ddbc0c19190dL49 the MailChannel send the rendered view as an array (`['text' => 'toto', 'html' => '<p>toto</p>']`) to the mailer.

An exception is raised: Impossible to found the view `<p>toto</p>`.

**Comment by mattstauffer** [comment]
@ThibaudDauce Thanks for sharing this. Can you still reproduce it? I'm not seeing it at the moment but I'm sure there might be a specific setup that reproduces it. Thanks! Closing for now but please re-open if you can reproduce.
