### ISSUE TITLE
HTML Character Codes

### ISSUE THREAD

**Issue by psaunders** [tightenco/mailthief#64]
I noticed today that MT was failing out on HTML character codes when doing the ->contains() assertion.

Seeing as Laravel's tools (this was using notifications) default to rendering character codes should that be looked at? It would just be a matter of wrapping the "Contains" assertion in the e() helper function.

**Comment by mattstauffer** [comment]
@psaunders Great question. Is there any chance you could show us a sample bit of code for this? Thanks!

**Comment by MattStypa** [comment]
I can't replicate this, assuming I understand the problem. This is over 7 months old. Close it?

**Comment by mattstauffer** [comment]
@MattStypa My guess is that he is trying to `assertContains("something with a character like @45")` and it fails because that would be rendered as "something with a character like &amp;45" in the actual view.

Is that reproducible? And does it seem odd or normal?

**Comment by MattStypa** [comment]
I would argue that the assertion works as intended.

I would like to make sure that the character renders as HTML entity rather than its projection. Otherwise, it is possible to have false positives when testing for XSS injection.

**Comment by mattstauffer** [comment]
@MattStypa yah.. I was just thinking that. Good point and thanks for handling it.
