### ISSUE TITLE
[Feature Request] Handle multiple messages

### ISSUE THREAD

**Issue by ejunker** [tightenco/mailthief#72]
Many of the Mailthief methods assume you want to assert the last message sent. I have a situation where 2 emails are sent as part of one atomic process. 

I first tried to test like this but of course it doesn't work because it always uses the last message.

```php
$this->seeMessageWithSubject('New Registration');
$this->seeMessageWithSubject('Welcome to example.com');
```

Is there a way to test easily test this? Maybe something like this where you can specify the rank of the message to assert.

```php
$this->seeMessageWithSubject('New Registration', 1);
$this->seeMessageWithSubject('Welcome to example.com', 2);
```

Or maybe something like this using a fluent syntax on the `Message`

```php
$messages = $this->getMessages();
$messages[0]->assertSubject('New Registration');
$messages[1]->assertSubject('Welcome to example.com');
```

Or maybe just expose the assertions as methods

```php
$messages = $this->getMessages();
$this->assertMessageWithSubject($messages[0], 'New Registration');
```

**Comment by calebporzio** [comment]
You can use 
```
$this->seeInSubjects('New Registration');
```

It will look at all the message subjects for that message.

Thanks!
