### ISSUE TITLE
ErrorException: Undefined variable: message

### ISSUE THREAD

**Issue by vedmant** [tightenco/mailthief#74]
Hi, I have an error with my tests: ErrorException: Undefined variable: message in project/storage/framework/views/0e7b3bbec68c7d9d5c5a17188664fe42d79b3295.php:10

It looks like if I use InteractsWithMail trait, my views don't have $message variable anymore, I use it to embed images to my emails. It works fine if I remove InteractsWithMail trait from my test.

**Comment by calebporzio** [comment]
Hey @vedmant,

Thanks for bringing this to our attention. This issue should be fixed in the latest release: [0.3.7](https://github.com/tightenco/mailthief/releases/tag/v0.3.7)

`composer update tightenco/mailthief` and let me know if your problem is solved.

Thanks!
