### ISSUE TITLE
Undefined method addPart

### ISSUE THREAD

**Issue by mnabialek** [tightenco/mailthief#8]
I'm using code like this to send message:

```
        $mail->raw('text content',
            function ($message) {
                /** @var Message $message */
                $message->to('test@example.com', 'test')
                    ->subject('subject')
                    ->addPart('html content', 'text/html');
                    $message->replyTo('reply@example.com', 'reply');
                
            });
```

and using MailThief I'm getting:

> Fatal error: Call to undefined method MailThief\Message::addPart()

This is probably because in original Mailer class there is magic `__call` function that calls any extra methods from Swift Message and they are not implemented in `MailThief\Message`

**Comment by besologic** [comment]
Resolved in #36
