### ISSUE TITLE
Backwards compatibility break

### ISSUE THREAD

**Issue by FatBoyXPC** [tightenco/mailthief#83]
[This](https://github.com/tightenco/mailthief/commit/248e9049fd71fe23112992f8ba16b3f218d53daf) commit is not compatible with Laravel 5.2 :(

PHP 5.6.31
Laravel 5.2.45
PHPUnit 4.6.36

**Comment by mattstauffer** [comment]
Of course. I remembered that and planned to work around it and it totally slipped my mind. Thanks. Will fix ASAP.

**Comment by mattstauffer** [comment]
@FatBoyXPC Could you test this out?

https://github.com/tightenco/mailthief/commit/ade59e0df5697d59e2ac89331d0ff0c0015e340b

Not tagged, but you can edit your local vendor files to try it. Thanks!

**Comment by FatBoyXPC** [comment]
Bah, of course you beat me to it! I actually planned on submitting a PR for Hacktoberfest, but I wanted to write a test first to prove the bug in #81 was actually fixed!

**Comment by mattstauffer** [comment]
Feel free to PR that test!

**Comment by FatBoyXPC** [comment]
At first I thought this would be a pretty quick comparison test, but then I noticed the method was private and this got a little more difficult. It also then dawned on me that this is only a Laravel 5.5 problem, since this works fine in other versions of laravel.

In short, I'm a little lost on how to test this, but I would love some guidance on this as it would make for an excellent learning opportunity. On that note, if there's a way to ensure nothing breaks 5.0-5.2 compatibility via tests, I'd love some of that functionality, too.

I also noticed that there are some PHP7 exclusive features used in `TestCase` - so I feel like `composer.json` should have php 7 in `require-dev`.

**Comment by mattstauffer** [comment]
@FatBoyXPC TBH, I'm not sure how to do that either. You said you were planning on it so I was excited to learn. :)

w/r/t the PHP7-exclusive features, I'd rather we didn't require PHP 7 and instead fix that code in `TestCase`--I'd totally accept that PR if you want to make it. Thanks!

**Comment by FatBoyXPC** [comment]
Okay, fair deal! I'll certainly remove PHP 7 features in a PR soon, and
I'll see what I can do about this facades deal. I might just end up going
the easier route and see if I can wire up an integration test, if that ends
up being easier.
