### ISSUE TITLE
Inclusion of tap() breaks tests prior to 5.3

### ISSUE THREAD

**Issue by markdwhite** [tightenco/mailthief#84]
Well, updating to 0.3.11 broke tests here on 5.1 and tap() seems to have been included after 5.3.

Pinning to version 0.3.10 has fixed it, but given this is a breaking change shouldn't it be a new major version, or correctly designated in the composer.json, or at least documented somewhere?

**Comment by mattstauffer** [comment]
We fixed this a day or two ago and I just pushed 0.3.12 to get it out there for you.

**Comment by markdwhite** [comment]
Cool - thanks
