### ISSUE TITLE
Class 'MailThief\Arr' not found

### ISSUE THREAD

**Issue by screenager** [tightenco/mailthief#9]
I'm on the latest Laravel 5.2.39 , running in PHP 5.5.34, but when running a mail test with the hijack enabled I get : 

> Class 'MailThief\Arr' not found in …/vendor/tightenco/mailthief/src/MailThief.php on line 69

What's wrong?

**Comment by michaelachrisco** [comment]
It may be related to the version of PHP. Are you able to use 5.6+? 

I was able to get mailthief working with Laravel 5.2.39 on PHP 5.6 and PHP 7.0 here: 
[Laravel Services Talk](https://github.com/michaelachrisco/lara-services/blob/master/lara-services/tests/services/SendWelcomeEmailServiceTest.php)

**Comment by adamwathan** [comment]
Def a real bug :| Pushing a fix now.

**Comment by adamwathan** [comment]
Should be fixed for v0.1.1 👍
