### ISSUE TITLE
Lumen - Facade Accessor Returns Wrong Version

### ISSUE THREAD

**Issue by colonelpopcorn** [tightenco/mailthief#92]
I'm using Lumen v5.5.* and whenever I try to run `MailThief::hijack()` I get the following error:
```
In MailThiefFiveFourCompatible.php line 8:

  Declaration of MailThief\MailThiefFiveFourCompatible::queue($view, array $data, $callback, $queue = NULL) must b
  e compatible with Illuminate\Contracts\Mail\MailQueue::queue($view, $queue = NULL)

```

I changed the line in MailThief's `getFacadeAccessor()` method as shown below:
```
protected static function getFacadeAccessor()
    {
        return (float) /*self::$app->version()*/5.5 >= 5.5
            ? MailThiefFiveFiveCompatible::class
            : MailThiefFiveFourCompatible::class;
    }
```

When I do this the error goes away. I'd like to know what I can do to a) verify that Lumen is reporting the right version, and b) fix the bad reporting in Lumen for this package. Is it possible that the `self::$app->version()` method doesn't exist in Lumen?

**Comment by colonelpopcorn** [comment]
I found the issue. The `version()` method in Lumen returns a string instead of the version in float form.

[Application.php in lumen-framework](https://github.com/laravel/lumen-framework/blob/5.6/src/Application.php):
```
    /**
     * Get the version number of the application.
     *
     * @return string
     */
    public function version()
    {
        return 'Lumen (5.6.1) (Laravel Components 5.6.*)';
    }
```
Would it be better to take this issue to the lumen-framework or can I make a check for Lumen in your facade accessor?

**Comment by mattstauffer** [comment]
@colonelpopcorn great catch!! Let’s make the fix here—thanks!

**Comment by colonelpopcorn** [comment]
Okay, I'll get a pull request together.
