### ISSUE TITLE
Laravel 6.* and 7.* support

### ISSUE THREAD

**Issue by arubacao** [tightenco/mailthief#97]
Hey guys,

just wanted to ask if Laravel support for newer versions is planned.

Thanks

**Comment by mattstauffer** [comment]
Hey @arubacao! I know we looked into it and this was our final consensus:

> Due to changes in the way mail testing is handled by Laravel; MailThief is not needed for recent versions of the framework. MailThief will remain compatible with Laravel up to version 5.5.

Let us know if you have any other questions!
